### ISSUE TITLE
Docs are misleading

### ISSUE THREAD

**Issue by thezanke** [egoist/interpolate-html-plugin#1]
I didn't think the plugin was working since it says "then you can use %NODE_ENV%" but really the delimiters are `!!` by default, not `%`. Almost gave up but looked at the docs one more time and saw the piece at the bottom about the defaults and it clicked.

**Comment by egoist** [comment]
Hi, it's now fixed to `%NODE_ENV%`, but honestly I've ended up passing data via html-webpack-plugin's options directly.
