### ISSUE TITLE
TypeError: Cannot read property 'tap' of undefined when used with html-webpack-plugin 4.0.1

### ISSUE THREAD

**Issue by b3nk3** [egoist/interpolate-html-plugin#13]
I am building a sandbox for internal use, making sure we always get the latest versions of packages, when setting up a new sandbox. I can restrict this if need be, tho interested in getting it sorted.

**Comment by Benji1** [comment]
@b3nk3 @a-x- @keithgabryelski you do not need this plugin anymore, it was extracted from react-dev-utils. You can use a version working directly from there: https://github.com/facebook/create-react-app/tree/master/packages/react-dev-utils#new-interpolatehtmlpluginhtmlwebpackplugin-htmlwebpackplugin-replacements-keystring-string

**Comment by b3nk3** [comment]
Gosh, I found that out a few days after raising this ticket and I forgot to close it. Apologies.

Appreciate you taking the time to comment.
