### ISSUE TITLE
Inability to work with webpack@5 and html-webpack-plugin@^4.5.0

### ISSUE THREAD

**Issue by D-Pow** [egoist/interpolate-html-plugin#15]
Attempting to build using a simple config object as described in the specs fails due to ` TypeError: Cannot read property 'tap' of undefined`.

## Webpack config

    module.exports = {
        ...
        plugins: [
            new HtmlWebpackPlugin({
                title: indexHtmlTitle,
                template: paths.root + '/src/index.html',
                meta: indexHtmlMetaTagData
            }),
            new InterpolateHtmlPlugin(myConfigObj),
            ...
        ]
    };

## Output

    TypeError: Cannot read property 'tap' of undefined
        at \myapp\node_modules\interpolate-html-plugin\index.js:36:63
        at Hook.eval [as call] (eval at create

## Expected result

InterpolateHtmlPlugin to work as expected with webpack@5, html-webpack-plugin@^4.5.0, etc.

Edit: Added the HtmlWebpackPlugin config to plugins array to show that the suggestion in [issue 5](https://github.com/egoist/interpolate-html-plugin/issues/5) to put HtmlWebpackPlugin above InterpolateHtmlPlugin does not solve the issue.

**Comment by egoist** [comment]
Should be fixed in v4.0.0 (#14)
