### ISSUE TITLE
Cannot read property 'tap' of undefined

### ISSUE THREAD

**Issue by jamespantalones** [egoist/interpolate-html-plugin#7]
Getting this with `3.0.0` on Webpack `4.6.0`.  

```
compilation.hooks.htmlWebpackPluginBeforeHtmlProcessing.tap(
                                                              ^

TypeError: Cannot read property 'tap' of undefined
```

Called just with example opts

```js
new InterpolateHtmlPlugin({
      NODE_ENV: 'production'
   }),

    new HtmlWebpackPlugin({
      template: 'src/index.html',
      inject: false
    })
```

**Comment by jamespantalones** [comment]
closing. discovered `HTMLWebpackPlugin` needs to come before `InterpolateHtmlPlugin`, contrary to `create-react-app` setup

**Comment by rndm2** [comment]
Same issue when using with 'speed-measure-webpack-plugin'. 
Probably we need to reopen this issue to fix compatibility
